name: Deploy Resume to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload resume to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'  # Change if your resume is in a subfolder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
