name: Deploy Resume to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload resume to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'  # Make sure this points to your built output
          name: github-pages  # Ensure this name is not used anywhere else

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
